export const tags = [
  "a",
  "abbr",
  "address",
  "area",
  "article",
  "aside",
  "audio",
  "b",
  "base",
  "blockquote",
  "body",
  "br",
  "button",
  "canvas",
  "caption",
  "cite",
  "code",
  "col",
  "colgroup",
  "data",
  "datalist",
  "dd",
  "del",
  "details",
  "dfn",
  "dialog",
  "div",
  "dl",
  "dt",
  "em",
  "fieldset",
  "figcaption",
  "figure",
  "footer",
  "form",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "head",
  "header",
  "hgroup",
  "hr",
  "html",
  "i",
  "iframe",
  "img",
  "input",
  "ins",
  "kbd",
  "label",
  "legend",
  "li",
  "link",
  "main",
  "map",
  "mark",
  "math",
  "menu",
  "menuitem",
  "meta",
  "meter",
  "nav",
  "noscript",
  "object",
  "ol",
  "optgroup",
  "option",
  "output",
  "p",
  "param",
  "picture",
  "pre",
  "progress",
  "q",
  "s",
  "samp",
  "script",
  "search",
  "section",
  "select",
  "slot",
  "small",
  "source",
  "span",
  "strong",
  "style",
  "sub",
  "summary",
  "sup",
  "svg",
  "table",
  "tbody",
  "td",
  "template",
  "textarea",
  "tfoot",
  "th",
  "thead",
  "time",
  "title",
  "tr",
  "track",
  "u",
  "ul",
  "var",
  "video"
] as const;

export type Tag = (typeof tags)[number];
export const TagDescription: Record<Tag, string> = {
  a: "Defines a hyperlink",
  abbr: "Defines an abbreviation or an acronym",
  address: "Defines contact information for the author/owner of a document",
  area: "Defines an area inside an image-map",
  article: "Defines an article",
  aside:
    "Defines a section of a page that consists of content that is tangentially related to the content around it",
  audio: "Defines sound content",
  b: "Defines bold text",
  base: "Specifies the base URL/target for all relative URLs in a document",
  blockquote: "Defines a section that is quoted from another source",
  body: "Defines the document's body",
  br: "Defines a single line break",
  button: "Defines a clickable button",
  canvas:
    "Used to draw graphics, on the fly, via scripting (usually JavaScript)",
  caption: "Specifies the caption (or title) of a table",
  cite: "Defines the title of a work",
  code: "Defines a piece of computer code",
  col: "Specifies column properties for each column within a <colgroup> element",
  colgroup:
    "Specifies a group of one or more columns in a table for formatting",
  data: "Adds a machine-readable translation of a given content",
  datalist: "Specifies a list of pre-defined options for input controls",
  dd: "Defines a description/value of a term in a description list",
  del: "Defines text that has been deleted from a document",
  details:
    'Creates a disclosure widget in which information is visible only when the widget is toggled into an "open" state',
  dfn: "Used to indicate the term being defined within the context of a definition phrase or sentence",
  dialog:
    "Represents a dialog box or other interactive component, such as a dismissible alert, inspector, or subwindow.",
  div: "Defines a section in a document",
  dl: "Defines a description list",
  dt: "Defines a term/name in a description list",
  em: "Defines emphasized text ",
  embed:
    "Embeds external content at the specified point in the document. This content is provided by an external application or other source of interactive content such as a browser plug-in.",
  fieldset: "Groups related elements in a form",
  figcaption:
    "Represents a caption or legend describing the rest of the contents of its parent <figure> element.",
  figure:
    "Represents self-contained content, potentially with an optional caption, which is specified using the <figcaption> element. The figure, its caption, and its contents are referenced as a single unit.",
  footer: "Defines a footer for a document or section",
  form: "Defines an HTML form for user input",
  h1: "Defines HTML heading level 1",
  h2: "Defines HTML heading level 2",
  h3: "Defines HTML heading level 3",
  h4: "Defines HTML heading level 4",
  h5: "Defines HTML heading level 5",
  h6: "Defines HTML heading level 6",
  head: "Defines information about the document",
  header: "Defines a header for a document or section",
  hgroup: "Defines a group of headings",
  hr: "Defines a thematic change in the content",
  html: "Defines the root of an HTML document",
  i: "Defines a part of text in an alternate voice or mood",
  iframe: "Embed another HTML page into the current one",
  img: "Defines an image",
  input: "Defines an input control",
  ins: "Defines a text that has been inserted into a document",
  kbd: "Defines keyboard input",
  label: "Defines a label for an <input> element",
  legend: "Defines a caption for a <fieldset> element",
  li: "Defines a list item",
  link: "Defines the relationship between a document and an external resource (most used to link to style sheets)",
  main: "Specifies the main content of a document",
  map: "Used with <area> elements to define an image map (a clickable link area).",
  mark: "Defines marked/highlighted text",
  math: "Embed MathML content",
  menu: "A semantic alternative to <ul> representing an unordered list of <menuitem>.",
  menuitem:
    "Represents a command that a user is able to invoke through a popup menu. This includes context menus, as well as menus that might be attached to a menu button.",
  meta: "Defines metadata about an HTML document",
  meter:
    "Represents either a scalar value within a known range or a fractional value.",
  nav: "Defines navigation links",
  noscript:
    "Defines an alternate content for users that do not support client-side scripts",
  object:
    "Represents an external resource, which can be treated as an image, a nested browsing context, or a resource to be handled by a plugin.",
  ol: "Defines an ordered list",
  optgroup: "Defines a group of related options in a drop-down list",
  option: "Defines an option in a drop-down list",
  output:
    "Container element into which a site or app can inject the results of a calculation or the outcome of a user action.",
  p: "Defines a paragraph",
  param: "Defines a parameter for an object",
  picture:
    "Contains <source> elements and one <img> element to offer alternative versions of an image for different display/device scenarios.",
  pre: "Defines preformatted text",
  progress:
    "Displays an indicator showing the completion progress of a task, typically displayed as a progress bar.",
  q: "Defines a short quotation",
  s: "Defines text that is no longer correct",
  samp: "Defines sample output from a computer program",
  script: "Defines a client-side script",
  search:
    "	Represents a part that contains a set of form controls or other content related to performing a search or filtering operation.",
  section: "Defines a section in a document",
  select: "Defines a drop-down list",
  slot: "A placeholder inside a <template> used by Web Components that you can fill with markup coming from outside the Web Component",
  small: "Defines smaller text",
  source:
    "Specifies multiple media resources for a <picture>, <audio> or <video>, ommonly used to offer the same media content in multiple file formats in order to provide compatibility with a broad range of browsers",
  span: "Defines a section in a document",
  strong: "Defines important text",
  style: "Defines style information for a document",
  sub: "Defines subscripted text",
  summary:
    "Specifies a summary, caption, or legend inside a <details> element. Clicking the <summary> element toggles the state of the parent <details> element open and closed.",
  sup: "Defines superscripted text",
  svg: "Used to embed Scalable Vector Graphics (SVG) fragments inside SVG or HTML documents.",
  table: "Defines a table",
  tbody: "Groups the body content in a table",
  td: "Defines a cell in a table",
  template: "Defines a template",
  textarea: "Defines a multiline input control (text area)",
  tfoot: "Groups the footer content in a table",
  th: "Defines a header cell in a table",
  thead: "Groups the header content in a table",
  time: "Defines a date/time",
  title: "Defines a title for the document",
  tr: "Defines a row in a table",
  track: "Defines text tracks for media elements (<video> and <audio>)",
  u: "Defines text that should be stylistically different from normal text",
  ul: "Defines an unordered list",
  var: "Defines a variable",
  video: "Defines a video or movie",
  wbr: "Defines a possible line-break",
};
